### ISSUE TITLE
Error when trying to install plugin from October Cms

### ISSUE THREAD

**Issue by beatriznbarroso** [rluders/jwtauth-plugin#61]
Hi, I am trying to use this plugin in October CMS and I was wondering if it is still available at OctoberCMS.

I get this error when I try to install the plugin:

Authority to provide product "rluders/jwtauth-plugin" could not be found

**Comment by rluders** [comment]
Hi @beatriznbarroso 

I need to check it. I would say that the plugin should work, 'cause the [last release](https://github.com/rluders/oc-jwtauth-plugin/releases/tag/v1.4.4) still fully compatible with OctoberCMS.

**Comment by josephcrowell** [comment]
My pull request that you approved was a conversion completely to Winter CMS, dropping support for OctoberCMS.

That's why I also asked you to rename the project to wn-jwtauth-plugin.

**Comment by rluders** [comment]
@josephcrowell yeap. But the last version that was released to OctoberCMS was working properly.

I'm on vacation, once I'm back home next week, I'll check it. The ideia is to keep both versions supported. But I need to figure out how to do it in only repository.

**Comment by josephcrowell** [comment]
:/ It looks like they pulled your plugin from the marketplace. https://octobercms.com/plugins?search=jwt

**Comment by rluders** [comment]
Yes. It is disabled for now.

**Comment by rluders** [comment]
Just a quick update here about some of my ideas to support both OctoberCMS and WinterCMS

- rename the repository to `jwtauth-plugin`
- create a separated branch for each platform
- add a suffix to the release tags to indicate its support version (e.g. `v2.1-oc` and `v2.1-wn`)
- change the release process to OctoberCMS marketplace

**Comment by rluders** [comment]
OctoberCMS will no longer be supported by this plugin.
